# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_auto_20160707_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
