# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0003_institutions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='institutions',
            new_name='institution',
        ),
    ]
