# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0007_auto_20160707_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='institution',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Installation'),
        ),
    ]
