# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0008_auto_20160714_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Installation'),
        ),
    ]
