# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0009_auto_20160714_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.Installation'),
        ),
    ]
