# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0017_auto_20160720_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.Installation'),
        ),
    ]
