# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 19:47
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0018_auto_20160725_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.Installation'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0000'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='institution',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0000'), max_digits=9),
        ),
    ]
